// <auto-generated />
namespace DeliveriandoWebApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _15 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_15));
        
        string IMigrationMetadata.Id
        {
            get { return "201311060001542_15"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
