// <auto-generated />
namespace DeliveriandoWebApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class j : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(j));
        
        string IMigrationMetadata.Id
        {
            get { return "201311241639019_j"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
