// <auto-generated />
namespace DeliveriandoWebApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class special : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(special));
        
        string IMigrationMetadata.Id
        {
            get { return "201311162205259_special"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
