// <auto-generated />
namespace DeliveriandoWebApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class deleteuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteuser));
        
        string IMigrationMetadata.Id
        {
            get { return "201311170417430_deleteuser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
