// <auto-generated />
namespace DeliveriandoWebApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _18 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_18));
        
        string IMigrationMetadata.Id
        {
            get { return "201311081550388_18"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
